<!-- 상단 Header -->
<div id="header">
<div class="header_area">
<h1 class="logo"><a href="/"><img alt="ONSUNDAY" src="/images/common/head_logo.png" /></a></h1>
<a class="head_btn head_user" href="<?=$_SERVER['PHP_SELF']?>?pid=25"><img alt="프로필" src="/images/common/head_user.png" /></a> <a class="head_btn head_search" href="#"><img alt="검색" src="/images/common/head_search.png" /></a></div>
</div>
<!-- // 상단 Header -->